name: Deploy Kitcham's Friends Json

on:
  # Trigger action when push and push-request
  push: 
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  YML2JSON:
    name: Release json
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    
    # Set up python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # install pyYAML
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install pyyaml
    
    # Pyhton script
    - name: Generation  
      run: | 
        python generate.py
        echo `date +"%Y-%m-%d %H:%M:%S"` updated > update.log

    # Commit json into repo
    - name: Commit
      run: |
        git config --global user.email tjj386@qq.com
        git config --global user.name Kitcham
        git add .
        git commit -m "feat(json): update YML and generate JSON successfully" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
